IslyObject omit method.
utily/isly pull request #21
Opened 2023-11-07 13:35 UTC by AntonCroner

2023-11-08 07:58 UTC, tvartom commented
Don't forget to update `README.md`. (And remove it from `.vscode/settings.json`-> `files.exclude` coz that is just stupid.)

2023-11-08 08:04 UTC, tvartom commented
Methods should be possible to use without providing generics. (`type.omit(["a"])` should be the same as `type.omit<"a">(["a"])`).
Which I think it is, but there is no test for it.

2023-11-08 08:11 UTC, tvartom commented
Also add a test with omit used on an extended object. Both removing from the direct parent, and from further down, to make sure this also works.

2023-11-08 20:28 UTC, tvartom commented
I fixed the extended, rewrote the omit, added pick and updated readme.

2023-11-10 08:28 UTC, tvartom approved these changes

2023-11-10 13:36 UTC, marcushanses requested changes

2023-11-10 13:36 UTC, marcushanses commented on object.spec.ts
> +	})
Remove empty lines.

2023-12-11 14:45 UTC, marcushanses approved these changes

2023-12-11 14:46 UTC, merged